import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/ui/dashboard/sidebar/Sidebar";
import Navbar from "@/components/ui/dashboard/navbar/Navbar";
import styles from '../components/ui/dashboard/dashboard.module.css'
import Footer from "@/components/ui/dashboard/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.container}>
          <div className={styles.menu}>
            <Sidebar/>
          </div>
          <div className={styles.content}>
            <Navbar/>
            {children}
            <Footer/>
          </div>
        </div>
        </body>
    </html>
  );
}
